retry ansible package

diff --git a/.github/workflows/e2e-tests.yml b/.github/workflows/e2e-tests.yml
--- a/.github/workflows/e2e-tests.yml
+++ b/.github/workflows/e2e-tests.yml
@@ -422,8 +422,19 @@ jobs:
       - name: "Deps: Running SF"
         run: |
           set -xueo pipefail
-          sudo add-apt-repository --yes --update ppa:ansible/ansible
-          sudo apt-get install --assume-yes ansible
+
+          # Helper method to avoid failing from a network hiccup during provision
+          function tryharderto() {
+            i=0
+            until "$@"; do
+              ((++i <= 3))
+              echo >&2 "Retrying ${i}"
+              sleep 2m
+            done
+          }
+
+          tryharderto sudo add-apt-repository --yes --update ppa:ansible/ansible
+          tryharderto sudo apt-get install --assume-yes ansible
           cd deploy
           ansible-playbook dev-server.playbook.yml --limit localhost --diff
 
